# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'graph_coloring_problem/untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class OpenFile(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(168, 43)
        Dialog.setMinimumSize(QtCore.QSize(168, 43))
        Dialog.setMaximumSize(QtCore.QSize(168, 43))
        self.open_file = QtWidgets.QPushButton(Dialog)
        self.open_file.setGeometry(QtCore.QRect(40, 10, 89, 25))
        self.open_file.setMinimumSize(QtCore.QSize(89, 25))
        self.open_file.setMaximumSize(QtCore.QSize(89, 25))
        self.open_file.setObjectName("open_file")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.open_file.setText(_translate("Dialog", "打开文件"))
